"""Abstract base class for Argox processors that transform agent data in-flight."""

from abc import ABC, abstractmethod
from argox.core.context import RunContext


class ArgoxProcessor(ABC):
    """
    Base class for processors that transform data during agent execution.
    
    An ArgoxProcessor is an extensible component that synchronously transforms
    data "in-flight" (in real-time) during the agent's execution flow. This occurs
    before data reaches the LLM, tools, or the end user. Common use cases include
    personally identifiable information (PII) redaction, secret sanitization, and
    data normalization.
    
    Unlike OpenTelemetry's SpanProcessor which transforms telemetry data,
    ArgoxProcessor transforms actual agent data.
    """

    @abstractmethod
    async def process_input(self, text: str, ctx: RunContext) -> str:
        """
        Transform the user prompt before sending it to the LLM.
        
        This method is called to process and potentially modify the input text
        (user prompt) before it reaches the language model. Common transformations
        include PII redaction, content sanitization, or request normalization.
        
        Args:
            text: The original user prompt or input text.
            ctx: The execution context (RunContext) containing request metadata
                 and state information.
        
        Returns:
            The transformed input text ready to be sent to the LLM.
        """
        pass

    @abstractmethod
    async def process_tool_args(self, tool_name: str, args: dict, ctx: RunContext) -> dict:
        """
        Transform or validate tool call arguments before tool execution.
        
        This method is called to process and potentially modify the arguments
        that will be passed to a tool before its execution. Common transformations
        include parameter sanitization, secret redaction, or input validation.
        
        Args:
            tool_name: The name of the tool being called.
            args: The original tool arguments as a dictionary.
            ctx: The execution context (RunContext) containing request metadata
                 and state information.
        
        Returns:
            The transformed tool arguments ready for tool execution.
        """
        pass

    @abstractmethod
    async def process_output(self, text: str, ctx: RunContext) -> str:
        """
        Transform, clean, or audit the LLM response before returning to the user.
        
        This method is called to process and potentially modify the output text
        generated by the LLM before it reaches the end user. Common transformations
        include PII removal, content filtering, audit logging, or response normalization.
        
        Args:
            text: The original output text generated by the LLM.
            ctx: The execution context (RunContext) containing request metadata
                 and state information.
        
        Returns:
            The transformed output text ready to be returned to the user.
        """
        pass