"""Core data model for Argox agent run metrics."""

from __future__ import annotations

import time
import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone


@dataclass
class ToolCallRecord:
    """Record of a single tool invocation during an agent run.

    Args:
        name: Tool name as registered in the agent.
        start: Unix timestamp when the call started.
        end: Unix timestamp when the call completed. None if still in progress.
        result: Serialized output of the tool, if any.
        blocked: True if the policy engine prevented this call.
        block_reason: Human-readable reason the call was blocked.
    """

    name: str
    start: float
    end: float | None = None
    result: str | None = None
    blocked: bool = False
    block_reason: str | None = None

    @property
    def duration(self) -> float:
        """Elapsed seconds between start and end. Returns 0.0 if still running."""
        return (self.end - self.start) if self.end is not None else 0.0


@dataclass
class ApiCallRecord:
    """Token usage for a single LLM API call.

    Args:
        call_number: 1-based index of this call within the run.
        input_tokens: Tokens consumed by the prompt.
        output_tokens: Tokens generated by the model.
        total_tokens: Sum of input and output tokens.
    """

    call_number: int
    input_tokens: int
    output_tokens: int
    total_tokens: int


@dataclass
class AgentRunMetrics:
    """Accumulated metrics and context for one complete agent execution.

    All list/dict fields default to empty collections. Scalar fields with
    defaults allow construction with only ``agent_name`` for convenience in
    tests and simple integrations.

    Args:
        agent_name: Logical name of the agent (e.g. ``"triage-bot"``).
        run_id: Unique identifier for this run. Auto-generated if not provided.
        agent_version: Semantic version string of the agent definition.
        prompt: Raw user prompt that initiated the run.
        timestamp: ISO-8601 UTC timestamp of when the run was created.
        final_output: Final text returned to the user after output policy checks.
        success: True only when the run completed without unhandled errors.
        start_time: Unix timestamp recorded at run creation.
        end_time: Unix timestamp recorded when the run finished. None if ongoing.
        api_calls: Ordered list of per-call token records.
        tools_available: Names of tools exposed to the agent after policy filtering.
        tools_blocked: Tools removed by the policy engine before agent execution.
        tools_called: Ordered records of every tool invocation during the run.
        input_policy_passed: False if the input policy blocked or flagged the prompt.
        output_policy_passed: False if the output policy blocked or flagged the result.
        policy_violations: Human-readable messages for each policy violation.
        exporter_errors: Error strings collected when an exporter raises during export.
            Each entry is formatted as ``"ExporterClassName: <error message>"``.
            A non-empty list means at least one exporter failed; the run outcome itself
            is unaffected.
    """

    agent_name: str = ""
    run_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    agent_version: str = ""
    prompt: str = ""
    timestamp: str = field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )

    # Result
    final_output: str = ""
    success: bool = False

    # Timing
    start_time: float = field(default_factory=time.time)
    end_time: float | None = None

    # Token tracking
    api_calls: list[ApiCallRecord] = field(default_factory=list)

    # Tool tracking
    tools_available: list[str] = field(default_factory=list)
    tools_blocked: list[dict] = field(default_factory=list)
    tools_called: list[ToolCallRecord] = field(default_factory=list)

    # Policy tracking
    input_policy_passed: bool = True
    output_policy_passed: bool = True
    policy_violations: list[str] = field(default_factory=list)

    # Export tracking
    exporter_errors: list[str] = field(default_factory=list)

    @property
    def duration(self) -> float:
        """Elapsed seconds from start to end. Returns 0.0 if still running."""
        return (self.end_time - self.start_time) if self.end_time is not None else 0.0

    @property
    def total_input_tokens(self) -> int:
        """Sum of input tokens across all API calls."""
        return sum(c.input_tokens for c in self.api_calls)

    @property
    def total_output_tokens(self) -> int:
        """Sum of output tokens across all API calls."""
        return sum(c.output_tokens for c in self.api_calls)

    @property
    def total_tokens(self) -> int:
        """Sum of all tokens (input + output) across all API calls."""
        return sum(c.total_tokens for c in self.api_calls)

    def to_dict(self) -> dict:
        """Serialize to a JSON-compatible dict for exporters and logging."""
        return {
            "run_id": self.run_id,
            "agent_name": self.agent_name,
            "agent_version": self.agent_version,
            "timestamp": self.timestamp,
            "prompt": self.prompt,
            "final_output": self.final_output,
            "success": self.success,
            "duration_seconds": round(self.duration, 3),
            "tokens": {
                "input": self.total_input_tokens,
                "output": self.total_output_tokens,
                "total": self.total_tokens,
                "by_api_call": [
                    {
                        "call": c.call_number,
                        "input": c.input_tokens,
                        "output": c.output_tokens,
                        "total": c.total_tokens,
                    }
                    for c in self.api_calls
                ],
            },
            "tools": {
                "available": self.tools_available,
                "blocked": self.tools_blocked,
                "called": [
                    {
                        "name": t.name,
                        "duration": round(t.duration, 3),
                        "result": t.result,
                        "blocked": t.blocked,
                        "block_reason": t.block_reason,
                    }
                    for t in self.tools_called
                ],
            },
            "policies": {
                "input_passed": self.input_policy_passed,
                "output_passed": self.output_policy_passed,
                "violations": self.policy_violations,
            },
            "exporter_errors": self.exporter_errors,
        }
