/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List audit entries
         * @description Return up to ``limit`` entries in sequence order, starting at ``offset``.
         *
         *     ``offset`` is a zero-based entry index so the whole log can be paged
         *     through, not only its first ``limit`` entries. A corrupt record stops the
         *     listing with ``malformed=True`` instead of raising a 500 (mirroring
         *     ``/verify``).
         */
        get: operations["list_entries"];
        put?: never;
        /**
         * Append an audit entry
         * @description Append an event to the audit log and return the sealed entry.
         *
         *     ``actor`` is the authenticated principal, not a client-supplied value.
         */
        post: operations["append_entry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Verify the audit hash chain
         * @description Walk the hash chain and report the first broken link, if any.
         */
        get: operations["verify_chain"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List API keys
         * @description List every key's non-secret metadata, newest first.
         */
        get: operations["list_keys"];
        put?: never;
        /**
         * Create an API key
         * @description Mint a new API key and return its raw secret once.
         */
        post: operations["create_key"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/keys/{key_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke an API key
         * @description Revoke a key. Idempotent: revoking an unknown/already-revoked key is 404.
         */
        delete: operations["revoke_key"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/cost": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Cost metrics
         * @description Total run cost (USD) over the trailing window.
         */
        get: operations["get_metrics_cost"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/latency": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Latency metrics
         * @description Average and p95 root-span latency over the trailing window.
         */
        get: operations["get_metrics_latency"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/success": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Success rate metrics
         * @description Run success rate over the trailing window.
         */
        get: operations["get_metrics_success"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/policies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List policies
         * @description List policy summaries straight from the manifest, sorted by id.
         *
         *     Sorting makes pagination deterministic regardless of manifest insertion
         *     order, and serving from the manifest alone keeps the endpoint O(1) blob
         *     reads no matter how many policies exist.
         */
        get: operations["list_policies"];
        put?: never;
        /**
         * Create a policy
         * @description Create a new policy as version 1.
         */
        post: operations["create_policy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/policies/bundle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Merged policy bundle (YAML)
         * @description Merge the rules of every active policy into one SDK-consumable YAML.
         *
         *     The response is a valid ``PolicyDocument`` for the SDK parser. The ETag
         *     is the SHA-256 of the YAML body, so it only changes when the effective
         *     rule set changes; ``If-None-Match`` hits answer ``304``. This handler
         *     never writes — GET stays idempotent and proxy-cacheable.
         */
        get: operations["get_bundle"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/policies/{policy_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get active policy
         * @description Return the active version of a policy.
         *
         *     A policy without an active version (draft or archived) is 404: clients
         *     must never mistake a retired document for an enforceable one.
         */
        get: operations["get_active_policy"];
        /**
         * Update a policy
         * @description Create version n+1 of an existing policy.
         *
         *     The version number is taken from the manifest read inside the CAS cycle,
         *     so two concurrent updates can never both commit the same number: the
         *     loser's manifest write fails and it retries against the new state.
         */
        put: operations["update_policy"];
        post?: never;
        /**
         * Archive a policy
         * @description Archive a policy by committing a new ``archived`` version.
         *
         *     History is preserved — nothing is deleted. Archiving an already-archived
         *     policy is idempotent: it returns the current head without writing a new
         *     version, keeping the response shape identical to the first call.
         */
        delete: operations["archive_policy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/policies/{policy_id}/v{version}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a specific policy version
         * @description Return one specific committed version of a policy.
         *
         *     The lookup goes through the manifest, so blobs that were written but
         *     never committed (lost CAS races) are not reachable here.
         */
        get: operations["get_policy_version"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List runs
         * @description List run summaries, newest first, with optional filters.
         *
         *     Rows are lightweight (no ``prompt``/``final_output``); ``from``/``to``
         *     bound the collector ingest time as a half-open ``[from, to)`` interval.
         */
        get: operations["list_runs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/by-trace/{trace_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get run detail by trace id
         * @description Return the run record joined from a span's ``trace_id``.
         *
         *     Returns 404 when no run was exported for the trace (the SDK's
         *     ``HttpRunExporter`` was not wired), so a span without a run is
         *     distinguishable from a missing trace.
         */
        get: operations["get_run_by_trace"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get run detail
         * @description Return the full run record for ``run_id`` (byte-equivalent blob).
         */
        get: operations["get_run"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/traces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List traces
         * @description List trace summaries, newest first.
         */
        get: operations["list_traces"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/traces/{trace_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get trace detail
         * @description Return the full span waterfall of one trace.
         */
        get: operations["get_trace"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Return ``ok`` when the process is alive and serving requests.
         */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Report whether the service is ready to accept traffic.
         *
         *     Probes the configured storage backend so orchestrators can drop the
         *     replica from rotation when the blob layer is unreachable. Returns
         *     ``503`` (still with the structured ``checks`` payload) on degradation
         *     so standard readiness probes react without parsing the body.
         *     Audit log checks will be added in later COL-* tickets.
         *
         *     Declared as a synchronous handler so FastAPI runs it in the thread
         *     pool: the storage health check performs blocking network I/O on the
         *     Azure driver and would otherwise stall the event loop.
         */
        get: operations["readyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Agent run-summary ingest
         * @description Accept one or a batch of run records and persist them.
         *
         *     Validates the payload synchronously, then either delegates persistence to
         *     a background task (``202``) or, when ``X-Argox-Durable: true`` is set, runs
         *     it in the threadpool and returns ``200`` only once committed.
         */
        post: operations["ingest_runs"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/traces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * OTLP/HTTP trace ingest
         * @description Accept an OTLP ``ExportTraceServiceRequest`` and persist its spans.
         *
         *     Validates the batch synchronously, then delegates the blob write and index
         *     insert to a background task and returns ``202 Accepted``. When the request
         *     carries ``X-Argox-Durable: true`` the persistence runs synchronously and the
         *     endpoint returns ``200 OK`` only once the data is committed.
         */
        post: operations["ingest_traces"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ApiKeyCreate
         * @description Request body for ``POST /api/v1/keys``.
         */
        ApiKeyCreate: {
            /** Expires In */
            expires_in?: number | null;
            /** Name */
            name: string;
            /** Scopes */
            scopes: string[];
        };
        /**
         * ApiKeyCreateResponse
         * @description Create response: the metadata view plus the one-time raw secret.
         */
        ApiKeyCreateResponse: {
            /** Created At */
            created_at: string;
            /** Created By */
            created_by?: string | null;
            /** Expires At */
            expires_at?: string | null;
            /** Id */
            id: string;
            /** Key */
            key: string;
            /** Key Prefix */
            key_prefix: string;
            /** Name */
            name: string;
            /** Revoked */
            revoked: boolean;
            /** Revoked At */
            revoked_at?: string | null;
            /** Scopes */
            scopes: string[];
        };
        /** ApiKeyListResponse */
        ApiKeyListResponse: {
            /** Keys */
            keys: components["schemas"]["ApiKeyView"][];
            /** Total */
            total: number;
        };
        /**
         * ApiKeyView
         * @description Non-secret view of a stored key.
         */
        ApiKeyView: {
            /** Created At */
            created_at: string;
            /** Created By */
            created_by?: string | null;
            /** Expires At */
            expires_at?: string | null;
            /** Id */
            id: string;
            /** Key Prefix */
            key_prefix: string;
            /** Name */
            name: string;
            /** Revoked */
            revoked: boolean;
            /** Revoked At */
            revoked_at?: string | null;
            /** Scopes */
            scopes: string[];
        };
        /**
         * AuditAppendRequest
         * @description Body of ``POST /api/v1/audit``.
         *
         *     ``actor`` is intentionally absent: it is bound to the authenticated
         *     principal, never read from the request, so an entry cannot be forged under
         *     another identity.
         *
         *     Provide either ``payload`` (hashed server-side into a digest so the raw
         *     value is never persisted) or a pre-computed ``payload_digest`` — not both.
         *     Omitting both records the digest of an empty payload.
         */
        AuditAppendRequest: {
            /** Action */
            action: string;
            /**
             * Kind
             * @default event
             */
            kind: string;
            /** Payload */
            payload?: unknown | null;
            /** Payload Digest */
            payload_digest?: string | null;
            /** Target */
            target: string;
        };
        /**
         * AuditEntryResponse
         * @description One persisted, hash-chained audit entry.
         */
        AuditEntryResponse: {
            /** Action */
            action: string;
            /** Actor */
            actor: string;
            /** Hash */
            hash: string;
            /** Kind */
            kind?: string | null;
            /** Payload Digest */
            payload_digest: string;
            /** Prev Hash */
            prev_hash: string;
            /** Seq */
            seq: number;
            /** Target */
            target: string;
            /** Timestamp */
            timestamp: string;
        };
        /**
         * AuditListResponse
         * @description A bounded slice of the chain, oldest first.
         *
         *     ``malformed`` is True when listing stopped early because a corrupt or
         *     truncated record was hit (mirroring ``/verify``); use ``/verify`` to locate
         *     the break. One bad line never fails the whole listing.
         */
        AuditListResponse: {
            /** Items */
            items: components["schemas"]["AuditEntryResponse"][];
            /** Limit */
            limit: number;
            /**
             * Malformed
             * @default false
             */
            malformed: boolean;
            /** Offset */
            offset: number;
            /** Returned */
            returned: number;
        };
        /**
         * AuditVerifyResponse
         * @description Result of walking the chain.
         *
         *     On a break, ``broken_kind`` and ``broken_target`` identify which kind of
         *     record failed and its ``run_id`` (kind ``run``) or ``trace_id`` (kind
         *     ``span_batch``); ``broken_offset`` is the zero-based position usable as the
         *     list endpoint's ``offset``. All are ``None`` when the chain is intact or
         *     when the broken record is too malformed to read.
         */
        AuditVerifyResponse: {
            /** Broken Kind */
            broken_kind?: string | null;
            /** Broken Offset */
            broken_offset?: number | null;
            /** Broken Seq */
            broken_seq?: number | null;
            /** Broken Target */
            broken_target?: string | null;
            /** Ok */
            ok: boolean;
            /** Reason */
            reason?: string | null;
            /** Total Entries */
            total_entries: number;
        };
        /**
         * CostMetricsResponse
         * @description Aggregated cost over a trailing window.
         */
        CostMetricsResponse: {
            /** Total Cost */
            total_cost: number;
            /** Trace Count */
            trace_count: number;
            /** Window Hours */
            window_hours: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Payload returned by the liveness endpoint.
         */
        HealthResponse: {
            /** Service */
            service: string;
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /**
         * LatencyMetricsResponse
         * @description Aggregated root-span latency over a trailing window.
         */
        LatencyMetricsResponse: {
            /** Avg Latency Ms */
            avg_latency_ms: number;
            /** P95 Latency Ms */
            p95_latency_ms: number;
            /** Trace Count */
            trace_count: number;
            /** Window Hours */
            window_hours: number;
        };
        /**
         * PolicyCreate
         * @description Request body for ``POST /api/v1/policies``.
         */
        PolicyCreate: {
            /** Created By */
            created_by?: string | null;
            /** Id */
            id: string;
            /** Rules */
            rules: components["schemas"]["PolicyRule"][];
            /**
             * Status
             * @default draft
             * @enum {string}
             */
            status: "active" | "draft" | "archived";
        };
        /** PolicyListResponse */
        PolicyListResponse: {
            /** Policies */
            policies: components["schemas"]["PolicySummary"][];
            /** Total */
            total: number;
        };
        /**
         * PolicyResponse
         * @description A stored policy version plus the hash addressing its blob.
         */
        PolicyResponse: {
            /** Content Hash */
            content_hash: string;
            /** Created By */
            created_by?: string | null;
            /** Id */
            id: string;
            /** Rules */
            rules: components["schemas"]["PolicyRule"][];
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "draft" | "archived";
            /** Updated At */
            updated_at?: string | null;
            /** Version */
            version: number;
        };
        /**
         * PolicyRule
         * @description Single enforcement rule; mirrors the SDK parser schema.
         */
        PolicyRule: {
            /**
             * Action
             * @enum {string}
             */
            action: "block" | "alert" | "ok";
            condition: components["schemas"]["RuleCondition"];
            /**
             * Enforcement
             * @default strict
             */
            enforcement: string;
            /** Id */
            id: string;
            /** Trigger */
            trigger: string;
        };
        /**
         * PolicySummary
         * @description Manifest-level view of one policy; no blob reads required.
         */
        PolicySummary: {
            /** Active Version */
            active_version?: number | null;
            /** Id */
            id: string;
            /** Latest Version */
            latest_version: number;
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "draft" | "archived";
        };
        /**
         * PolicyUpdate
         * @description Request body for ``PUT /api/v1/policies/{id}`` (creates version n+1).
         */
        PolicyUpdate: {
            /** Created By */
            created_by?: string | null;
            /** Rules */
            rules: components["schemas"]["PolicyRule"][];
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "draft" | "archived";
        };
        /**
         * ReadinessResponse
         * @description Payload returned by the readiness endpoint.
         */
        ReadinessResponse: {
            /** Checks */
            checks: {
                [key: string]: string;
            };
            /** Service */
            service: string;
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /**
         * RuleCondition
         * @description Single comparison inside a rule; mirrors the SDK parser schema.
         */
        RuleCondition: {
            /** Metric */
            metric: string;
            /**
             * Operator
             * @enum {string}
             */
            operator: "eq" | "neq" | "gt" | "gte" | "lt" | "lte" | "contains" | "in";
            /** Threshold */
            threshold: unknown;
        };
        /**
         * RunDetail
         * @description Full run record returned by the run-detail endpoints (COL-13).
         *
         *     The promoted columns are typed for the generated client; the original
         *     ``AgentRunMetrics`` payload carries more (prompt, final output, per-tool
         *     detail, per-call tokens, policy violations), so ``extra="allow"`` keeps
         *     them on the response. The handler returns the stored blob bytes verbatim
         *     when present, falling back to this projection of the index row otherwise.
         */
        RunDetail: {
            /** Agent Name */
            agent_name?: string | null;
            /** Agent Version */
            agent_version?: string | null;
            /** Cost Usd */
            cost_usd?: number | null;
            /** Duration Seconds */
            duration_seconds?: number | null;
            /** Model */
            model?: string | null;
            /** Run Id */
            run_id: string;
            /** Success */
            success?: boolean | null;
            /** Timestamp */
            timestamp?: string | null;
            /**
             * Tokens
             * @default {}
             */
            tokens: {
                [key: string]: unknown;
            };
            /** Trace Id */
            trace_id?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * RunListResponse
         * @description Paginated payload returned by ``GET /api/v1/runs``.
         */
        RunListResponse: {
            /** Items */
            items: components["schemas"]["RunSummary"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /**
         * RunRecordIn
         * @description A single ``AgentRunMetrics``-shaped run record.
         *
         *     Mirrors :meth:`argox.core.state.AgentRunMetrics.to_dict`. Only ``run_id``
         *     is required; everything else defaults so partial records still index. The
         *     Collector does not scrub content (PII redaction is the SDK's job) and
         *     preserves unknown fields on the immutable blob via ``extra="allow"``.
         *
         *     ``trace_id`` is optional and top-level: the SDK exporter (EXP-09) sets it
         *     so the Query API can join a span back to its run. ``cost_usd`` is left
         *     unset at ingest and backfilled from ``model`` and the token totals
         *     (COL-17).
         */
        RunRecordIn: {
            /**
             * Agent Name
             * @default
             */
            agent_name: string;
            /**
             * Agent Version
             * @default
             */
            agent_version: string;
            /** Cost Usd */
            cost_usd?: number | null;
            /** Duration Seconds */
            duration_seconds?: number | null;
            /** Model */
            model?: string | null;
            /** Run Id */
            run_id: string;
            /** Success */
            success?: boolean | null;
            /** Timestamp */
            timestamp?: string | null;
            tokens?: components["schemas"]["RunTokens"];
            /** Trace Id */
            trace_id?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * RunSummary
         * @description Lightweight, per-run row for the dashboard list view (COL-13).
         *
         *     The flat index projection only: ``prompt`` and ``final_output`` live on
         *     the blob and are deliberately excluded so a list response stays bounded
         *     regardless of run size. ``blob_path`` is an internal storage key and is
         *     not exposed.
         */
        RunSummary: {
            /** Agent Name */
            agent_name?: string | null;
            /** Agent Version */
            agent_version?: string | null;
            /** Cost Usd */
            cost_usd?: number | null;
            /** Duration Seconds */
            duration_seconds?: number | null;
            /** Model */
            model?: string | null;
            /** Run Id */
            run_id: string;
            /** Success */
            success?: boolean | null;
            /** Timestamp */
            timestamp?: string | null;
            /**
             * Total Input Tokens
             * @default 0
             */
            total_input_tokens: number;
            /**
             * Total Output Tokens
             * @default 0
             */
            total_output_tokens: number;
            /** Trace Id */
            trace_id?: string | null;
        };
        /**
         * RunTokens
         * @description Token totals carried by a run record.
         *
         *     Extra keys (e.g. ``total`` or ``by_api_call``) are preserved on the blob
         *     but ignored by the index, which only promotes the input/output totals.
         */
        RunTokens: {
            /**
             * Input
             * @default 0
             */
            input: number;
            /**
             * Output
             * @default 0
             */
            output: number;
        } & {
            [key: string]: unknown;
        };
        /**
         * SpanDetail
         * @description One span inside a trace waterfall.
         */
        SpanDetail: {
            /** Agent Name */
            agent_name?: string | null;
            /** Agent Version */
            agent_version?: string | null;
            /**
             * Attributes
             * @default {}
             */
            attributes: {
                [key: string]: unknown;
            };
            /** Duration Ms */
            duration_ms?: number | null;
            /** End Time */
            end_time?: string | null;
            /** Name */
            name?: string | null;
            /** Parent Span Id */
            parent_span_id?: string | null;
            /** Policy Decision */
            policy_decision?: string | null;
            /** Run Cost */
            run_cost?: number | null;
            /** Run Success */
            run_success?: boolean | null;
            /** Span Id */
            span_id: string;
            /** Start Time */
            start_time?: string | null;
        };
        /**
         * SuccessMetricsResponse
         * @description Aggregated run success rate over a trailing window.
         *
         *     ``success_rate`` is ``None`` when no runs reported an outcome inside the
         *     window, so an idle deployment is distinguishable from a failing one.
         */
        SuccessMetricsResponse: {
            /** Success Rate */
            success_rate?: number | null;
            /** Successful Runs */
            successful_runs: number;
            /** Total Runs */
            total_runs: number;
            /** Window Hours */
            window_hours: number;
        };
        /**
         * TraceDetailResponse
         * @description Full span waterfall returned by ``GET /api/v1/traces/{trace_id}``.
         *
         *     ``truncated`` is True when the trace exceeded the index's per-trace span
         *     ceiling and ``spans`` was cut to keep the response bounded.
         */
        TraceDetailResponse: {
            /** Spans */
            spans: components["schemas"]["SpanDetail"][];
            /** Trace Id */
            trace_id: string;
            /**
             * Truncated
             * @default false
             */
            truncated: boolean;
        };
        /**
         * TraceListResponse
         * @description Paginated payload returned by ``GET /api/v1/traces``.
         */
        TraceListResponse: {
            /** Items */
            items: components["schemas"]["TraceSummary"][];
            /** Limit */
            limit: number;
            /** Skip */
            skip: number;
            /** Total */
            total: number;
        };
        /**
         * TraceSummary
         * @description Aggregated, per-trace row for the dashboard list view.
         */
        TraceSummary: {
            /** Agent Name */
            agent_name?: string | null;
            /** Agent Version */
            agent_version?: string | null;
            /** Decision */
            decision: string;
            /** End Time */
            end_time?: string | null;
            /** Span Count */
            span_count: number;
            /** Start Time */
            start_time?: string | null;
            /** Status */
            status: string;
            /** Total Cost */
            total_cost?: number | null;
            /** Total Duration Ms */
            total_duration_ms?: number | null;
            /** Trace Id */
            trace_id: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_entries: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    append_entry: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuditAppendRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEntryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_chain: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditVerifyResponse"];
                };
            };
        };
    };
    list_keys: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyListResponse"];
                };
            };
        };
    };
    create_key: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApiKeyCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_key: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Key revoked (no body). */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No active key with that id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_metrics_cost: {
        parameters: {
            query?: {
                window_hours?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CostMetricsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_metrics_latency: {
        parameters: {
            query?: {
                window_hours?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LatencyMetricsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_metrics_success: {
        parameters: {
            query?: {
                window_hours?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessMetricsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_policies: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_policy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PolicyCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_bundle: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Merged PolicyDocument for the SDK parser. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/yaml": unknown;
                };
            };
            /** @description Bundle unchanged (If-None-Match matched). */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_active_policy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                policy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_policy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                policy_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PolicyUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_policy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                policy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_policy_version: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                policy_id: string;
                version: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs: {
        parameters: {
            query?: {
                agent?: string | null;
                success?: boolean | null;
                from?: string | null;
                to?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_by_trace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Run not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Run not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_traces: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
                trace_id?: string | null;
                agent_name?: string | null;
                status?: string | null;
                decision?: string | null;
                sort?: string | null;
                window_hours?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    readyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
    ingest_runs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunRecordIn"] | components["schemas"]["RunRecordIn"][];
            };
        };
        responses: {
            /** @description Run record(s) persisted synchronously (sent with X-Argox-Durable: true). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Run record(s) accepted for asynchronous persistence. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Durable persistence failed; the batch was not committed. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ingest_traces: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OTLP ExportTraceServiceResponse. Serialized as protobuf or JSON to match the request Content-Type. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "application/x-protobuf": unknown;
                };
            };
            /** @description Unsupported Content-Type. */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
